#include <stdio.h>


int main()
{
    int liczba[11],i,licznik=0;
    for(i=0;i<11;i++)
    {
        printf("Podaj liczbe: ");
        int x=scanf("%d",&liczba[i]);
        licznik++;
        if(x==0) return printf("Incorrect input"),1;
        if(liczba[i]<-10 || liczba[i]>10) return printf("Incorrect input data"),2;
        if(liczba[i]==0) break;
        if(licznik>11) break;
    }
    int j;
    for(j=0;j<licznik;j++)
    {
        if(liczba[j]==1)
        {
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf("\n");
          printf("\n");
        }
        if(liczba[j]==2)
        {
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf("\n");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("\n");
          printf("\n");
        }
        if(liczba[j]==3)
        {
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("\n");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("\n");
          printf("\n");
        }
        if(liczba[j]==4)
        {
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("\n");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("\n");
          printf("\n");
        }
        if(liczba[j]==5)
        {
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("\n");
          printf(" ");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("\n");
          printf(" ");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("X");
          printf("\n");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf("X");
          printf(" ");
          printf(" ");
          printf(" ");
          printf(" ");
          printf("X");
          printf("\n");
          printf("\n");
        }
        if(liczba[j]==6)
        {
          printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==7)
        {
          printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==8)
        {
          printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==9)
        {
          printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==10)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
        }
        if(liczba[j]==-1)
        {
          printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-2)
        {
          printf("X");
printf("X");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-3)
        {
          printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-4)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-5)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-6)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-7)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-8)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-9)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("\n");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("\n");
        }
        if(liczba[j]==-10)
        {
          printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("\n");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
printf(" ");
printf(" ");
printf("\n");
printf("X");
printf("X");
printf("X");
printf("X");
printf(" ");
printf(" ");
        }

    }
}
